// <auto-generated />
using System;
using Kcal.App.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kcal.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kcal.App.Models.ConsumedProducts", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataConsumo")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ConsumedProducts");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("094d7335-7b16-4d5b-a5fe-7447e7d17eb1"),
                            UserId = new Guid("6af0fffc-0f59-4298-9528-eeae4856d7f2"),
                            DataConsumo = new DateTime(2024, 10, 22, 23, 56, 8, 390, DateTimeKind.Utc).AddTicks(6140),
                            Quantidade = 1
                        },
                        new
                        {
                            ProductId = new Guid("dbb17be4-0d21-47a6-9513-c935e4a9b62b"),
                            UserId = new Guid("6af0fffc-0f59-4298-9528-eeae4856d7f2"),
                            DataConsumo = new DateTime(2024, 10, 22, 23, 56, 8, 390, DateTimeKind.Utc).AddTicks(6143),
                            Quantidade = 2
                        });
                });

            modelBuilder.Entity("Kcal.App.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int?>("Gramas")
                        .HasColumnType("int");

                    b.Property<int>("Kcal")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("094d7335-7b16-4d5b-a5fe-7447e7d17eb1"),
                            Categoria = "Fruta",
                            DataCadastro = new DateTime(2024, 10, 22, 23, 56, 8, 390, DateTimeKind.Utc).AddTicks(5926),
                            Gramas = 50,
                            Kcal = 20,
                            Marca = "Natural",
                            Nome = "Laranja"
                        },
                        new
                        {
                            Id = new Guid("dbb17be4-0d21-47a6-9513-c935e4a9b62b"),
                            Categoria = "Grãos",
                            DataCadastro = new DateTime(2024, 10, 22, 23, 56, 8, 390, DateTimeKind.Utc).AddTicks(5929),
                            Gramas = 100,
                            Kcal = 80,
                            Marca = "Namorado",
                            Nome = "Arroz"
                        });
                });

            modelBuilder.Entity("Kcal.App.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Altura")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetabolismoBasal")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6af0fffc-0f59-4298-9528-eeae4856d7f2"),
                            Altura = 180,
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(2024, 10, 22, 23, 56, 8, 390, DateTimeKind.Utc).AddTicks(5917),
                            MetabolismoBasal = 0,
                            Name = "Matheus",
                            Peso = 80,
                            Sexo = "M"
                        });
                });

            modelBuilder.Entity("Kcal.App.Models.ConsumedProducts", b =>
                {
                    b.HasOne("Kcal.App.Models.Product", "Product")
                        .WithMany("ConsumedProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kcal.App.Models.User", "User")
                        .WithMany("ConsumedProducts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kcal.App.Models.Product", b =>
                {
                    b.Navigation("ConsumedProducts");
                });

            modelBuilder.Entity("Kcal.App.Models.User", b =>
                {
                    b.Navigation("ConsumedProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
